# -*- ruby -*-

require_relative "../packages-red-data-tools-org-package-task"

class RedDataToolsArchiveKeyringPackageTask < PackagesRedDataToolsOrgPackageTask
  def initialize
    super("red-data-tools-archive-keyring",
          repository_version,
          latest_commit_time(File.join(__dir__, "..")))
  end

  private
  def define_archive_task
    file @archive_name do
      rm_rf(@archive_base_name)
      mkdir(@archive_base_name)
      sh("tar", "czf", @archive_name, @archive_base_name)
      rm_rf(@archive_base_name)
    end
  end

  def apt_targets_default
    [
      "debian-buster",
      "ubuntu-bionic",
      "ubuntu-focal",
    ]
  end

  def enable_yum?
    false
  end
end

task = RedDataToolsArchiveKeyringPackageTask.new
task.define
