# -*- ruby -*-

require_relative "../packages-red-data-tools-org-package-task"

class GRPackageTask < PackagesRedDataToolsOrgPackageTask
  def initialize
    super("gr",
          "0.57.1",
          Time.parse("2021-04-05"))
  end

  private
  def define_archive_task
    file @archive_name do
      base_url = "https://github.com/sciapp/gr/archive"
      original_archive_name = "v#{@version}.tar.gz"
      download("#{base_url}/#{original_archive_name}", original_archive_name)
      sh("tar", "xf", original_archive_name)
      version_txt_path = File.join(@archive_base_name, "version.txt")
      File.open(version_txt_path, "w") do |version_txt|
        version_txt.puts(@version)
      end
      sh("tar", "czf", @archive_name, @archive_base_name)
      rm_rf(@archive_base_name)
    end
  end

  def apt_targets_default
    [
      "debian-buster",
      "ubuntu-bionic",
      "ubuntu-focal",
      "ubuntu-groovy",
    ]
  end

  def yum_targets_default
    [
      "centos-8",
    ]
  end
end

task = GRPackageTask.new
task.define
