# -*- ruby -*-

require_relative "../packages-red-data-tools-org-package-task"

class GRPackageTask < PackagesRedDataToolsOrgPackageTask
  def initialize
    super("gr",
          "0.48.0",
          Time.parse("2020-03-14"))
  end

  private
  def define_archive_task
    file @archive_name do
      base_url = "https://github.com/sciapp/gr/archive"
      download("#{base_url}/v#{@version}.tar.gz", @archive_name)
    end
  end

  def apt_targets_default
    [
      "debian-buster",
      "ubuntu-bionic",
      "ubuntu-eoan",
    ]
  end

  def yum_targets_default
    [
      "centos-8",
    ]
  end
end

task = GRPackageTask.new
task.define
