# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  vms = [
    {
      :id => "centos-7-x86_64",
      :box => "bento/centos-7.3",
    },
  ]

  vms.each do |vm|
    config.vm.define(vm[:id]) do |node|
      node.vm.box = vm[:box]
      node.vm.provision(:shell, :path => "build-rpm.sh")
    end
  end
end
