# -*- ruby -*-

require_relative "../packages-red-data-tools-org-package-task"

class DuckDBPackageTask < PackagesRedDataToolsOrgPackageTask
  def initialize
    super("duckdb",
          "0.2.9",
          Time.parse("2021-09-06"))
  end

  private
  def define_archive_task
    file @archive_name do
      base_url = "https://github.com/duckdb/duckdb/archive"
      original_archive_name = "v#{@version}.tar.gz"
      download("#{base_url}/#{original_archive_name}", original_archive_name)
      sh("tar", "xf", original_archive_name)
      sh("tar", "czf", @archive_name, @archive_base_name)
      rm_rf(@archive_base_name)
    end
  end

  def apt_targets_default
    [
      "debian-buster",
      "debian-bullseye",
      "ubuntu-bionic",
      "ubuntu-focal",
      "ubuntu-hirsute",
    ]
  end

  def yum_targets_default
    [
      "centos-8",
    ]
  end
end

task = DuckDBPackageTask.new
task.define
