# -*- ruby -*-

require_relative "../packages-red-data-tools-org-package-task"

class DuckDBPackageTask < PackagesRedDataToolsOrgPackageTask
  def initialize
    super("duckdb",
          "1.4.2",
          Time.parse("2025-11-12"))
  end

  private
  def define_archive_task
    file @archive_name do
      base_url = "https://github.com/duckdb/duckdb/archive"
      original_archive_name = "v#{@version}.tar.gz"
      download("#{base_url}/#{original_archive_name}", original_archive_name)
      sh("tar", "xf", original_archive_name)
      sh("tar", "czf", @archive_name, @archive_base_name)
      rm_rf(@archive_base_name)
    end
  end

  def apt_targets_default
    [
      "debian-trixie",
      "ubuntu-jammy",
      "ubuntu-noble",
    ]
  end

  def yum_targets_default
    [
      "almalinux-10",
      "almalinux-9",
      "almalinux-8",
    ]
  end
end

task = DuckDBPackageTask.new
task.define
