- hosts: package-servers
  become: yes
  vars:
    ruby: ruby
    ruby_api_version: 3.3.0
    passenger_version: 6.1.2
  vars_files:
    - vars/private.yml
  tasks:
    # Base
    - name: Install base packages
      apt:
        name: "{{ item }}"
      with_items:
        - acpid
        - apg
        - apt-listchanges
        - cron
        - fail2ban
        - gcc
        - git
        - gpg
        - less
        - libc-dev
        - logrotate
        - make
        - rsync
        - ruby
        - ruby-dev
        - unattended-upgrades
        - vim
        - zsh
    - name: Use VIM as the default editor
      command: update-alternatives --set editor /usr/bin/vim.basic
    - name: Use e-mail for apt-listchanges
      lineinfile:
        path: /etc/apt/listchanges.conf
        regexp: "^frontend="
        line: "frontend=mail"
    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Reboot automatically when package upgrade requires restart
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: "^(//)?Unattended-Upgrade::Automatic-Reboot "
        line: "Unattended-Upgrade::Automatic-Reboot \"true\";"
    - name: Send notification when packages upgraded automatically
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: "^(//)?Unattended-Upgrade::Mail "
        line: "Unattended-Upgrade::Mail \"root\";"
    - name: Enable NTP
      command: timedatectl set-ntp true
    - name: "sudo: NOPASSWD"
      copy:
        src: etc/sudoers.d/sudo-nopasswd
        dest: /etc/sudoers.d/sudo-nopasswd
        mode: 0400
    - name: Install gems
      gem:
        name: "{{ item }}"
        state: latest
        user_install: no
      with_items:
        - base64
        - bundler
        - forwardable
        - stringio

    # User: packages
    - name: Create "packages" user
      user:
        name: packages
    - name: Create directories
      file:
        path: ~packages/{{ item }}
        state: directory
        owner: packages
        group: packages
      with_items:
        - bin/
        - public/
    - name: Put ~packages/.forward
      copy:
        content: "root"
        dest: ~packages/.forward
        owner: packages
        group: packages
    - name: Create ~packages/.ssh/
      file:
        path: ~packages/.ssh
        state: directory
        owner: packages
        group: packages
        mode: 0700
    - name: Put ~packages/.ssh/authorized_keys
      copy:
        src: home/packages/.ssh/authorized_keys
        dest: ~packages/.ssh/authorized_keys
        owner: packages
        group: packages
        mode: 0600
    - name: Create ~packages/.../
      file:
        path: ~packages/{{ item }}
        state: directory
        owner: packages
        group: packages
        mode: 0755
      with_items:
        - public
        - public/almalinux
        - public/almalinux/8
        - public/almalinux/9
        - public/debian
        - public/debian/dists
        - public/debian/pool/bookworm
        - public/debian/pool/trixie
        - public/ubuntu
        - public/ubuntu/dists
        - public/ubuntu/pool/focal
        - public/ubuntu/pool/jammy
        - public/ubuntu/pool/noble

    # User: rubygems-builder
    - name: Create "rubygems-builder" user
      user:
        name: rubygems-builder
    - name: Put ~rubygems-builder/.forward
      copy:
        content: "root"
        dest: ~rubygems-builder/.forward
        owner: rubygems-builder
        group: rubygems-builder
    - name: Clone builder
      become_user: rubygems-builder
      vars:
        ansible_ssh_pipelining: true
      git:
        repo: https://github.com/rubygems-ruby-4-0-ubuntu-24-04/builder.git
        dest: ~rubygems-builder/builder
    - name: Remove Gemfile.lock
      file:
        path: ~rubygems-builder/builder/webhook-receiver/Gemfile.lock
        state: absent
    - name: Update gems
      become_user: rubygems-builder
      shell: |
        bundle config set path vendor/bundle
        bundle install
      args:
        chdir: ~rubygems-builder/builder/webhook-receiver/
      notify:
        - Restart Apache
      vars:
        ansible_ssh_pipelining: true
    - name: Put configuration files
      template:
        src: home/rubygems-builder/builder/webhook-receiver/.github_token.jinja
        dest: /home/rubygems-builder/builder/webhook-receiver/.github_token
        owner: rubygems-builder
        group: rubygems-builder
        mode: 0600

    # Apache
    - name: Install Apache and related packages
      apt:
        name:
          - apache2
          - apache2-dev
          - build-essential
          - libapr1-dev
          - libaprutil1-dev
          - libcurl4-openssl-dev
          - libssl-dev
          - ruby-dev
          - zlib1g-dev
    - name: Keep more Apache logs
      lineinfile:
        path: /etc/logrotate.d/apache2
        regexp: "^    rotate "
        line: "    rotate 3650"
    - name: Put Apache configuration
      copy:
        src: "{{ item }}"
        dest: /{{ item }}
      with_items:
        - etc/apache2/sites-available/packages.red-data-tools.org.conf
    - name: Install Passenger
      gem:
        name: passenger
        version: "{{ passenger_version }}"
        user_install: no
      register: passenger
    - name: Build Passenger
      command: passenger-install-apache2-module --languages ruby --auto
      when: passenger.changed
    - name: Put Passenger configuration files
      template:
        src: etc/apache2/mods-available/{{ item }}.jinja
        dest: /etc/apache2/mods-available/{{ item }}
      with_items:
        - passenger.conf
        - passenger.load
      register: passenger_config_files
    - name: Enable Passenger
      command: a2enmod passenger
      when: passenger_config_files.changed
      notify:
        - Restart Apache
    - name: Enable our Apache configuration
      command: a2ensite packages.red-data-tools.org
    - name: Disable default Apache configuration
      command: a2dissite 000-default
      notify:
        - Restart Apache
    - name: Disable Apache modules
      command: a2dismod {{ item }}
      with_items:
        - mpm_event
        - mpm_prefork
    - name: Enable Apache modules
      command: a2enmod {{ item }}
      with_items:
        - mpm_worker
        - ssl
      notify:
        - Restart Apache

    # Let's Encrypt
    - name: "Install packages for Let's Encrypt"
      apt:
        name:
          - certbot
    - name: "packages: Check Let's Encrypt certificate"
      stat:
        path: /etc/letsencrypt/live/packages.red-data-tools.org/fullchain.pem
      register: packages_certificate
    - name: "mail: Check Let's Encrypt certificate"
      stat:
        path: /etc/letsencrypt/live/mail.red-data-tools.org/fullchain.pem
      register: mail_certificate
    - name: Check Apache is installed
      command: systemctl status apache2
      register: apache2_installed
      ignore_errors: yes
    - name: "Stop Apache before initializing Let's Encrypt certificate"
      service:
        name: apache2
        state: stopped
      when: apache2_installed.rc == 0 and
            ((not packages_certificate.stat.exists) or
             (not mail_certificate.stat.exists))
    - name: "packages: Initialize Let's Encrypt certificate"
      shell: |
        certbot certonly \
          --standalone \
          --non-interactive \
          --agree-tos \
          --email packages@red-data-tools.org \
          --domain packages.red-data-tools.org
      when: not packages_certificate.stat.exists
    - name: "mail: Initialize Let's Encrypt certificate"
      shell: |
        certbot certonly \
          --standalone \
          --non-interactive \
          --agree-tos \
          --email postmaster@red-data-tools.org \
          --domain mail.red-data-tools.org
      when: not mail_certificate.stat.exists
    - name: "Put Let's Encrypt update script"
      copy:
        src: etc/letsencrypt/renewal-hooks/{{ item }}
        dest: /etc/letsencrypt/renewal-hooks/{{ item }}
        mode: 0755
      with_items:
        - pre/stop-apache2
        - post/start-apache2

    # Postfix
    - name: Install Postfix
      apt:
        name:
          - postfix
    - name: Set /etc/aliases
      copy:
        src: etc/aliases
        dest: /etc/aliases
      notify:
        - Update /etc/aliases
    - name: Set /etc/mailname
      copy:
        content: "mail.red-data-tools.org"
        dest: /etc/mailname
    - name: Put Postfix configuration
      copy:
        src: etc/postfix/main.cf
        dest: /etc/postfix/main.cf
      notify:
        - Restart Postfix

    # milter manager
    - name: Add GPG key for APT repository
      get_url:
        url: https://packagecloud.io/milter-manager/repos/gpgkey
        dest: /etc/apt/keyrings/milter-manager.asc
    - name: Add APT repository for milter manager
      apt_repository:
        repo: |
          deb [signed-by=/etc/apt/keyrings/milter-manager.asc] https://packagecloud.io/milter-manager/repos/debian/ trixie main
        filename: "milter-manager"
    - name: Install milters
      apt:
        name:
          - milter-manager
          # - milter-greylist
    # - name: Add milter-manager user to greylist group
    #   user:
    #     name: milter-manager
    #     append: yes
    #     groups:
    #       - greylist
    #       - postfix
    # - name: Configure milter-greylist
    #   copy:
    #     src: "{{ item }}"
    #     dest: /{{ item }}
    #   with_items:
    #     - etc/milter-greylist/greylist.conf
    #     - etc/default/milter-greylist
    #   notify:
    #     - Restart milter-greylist
    - name: Create milter manager directory
      file:
        path: /var/spool/postfix/milter-manager/
        state: directory
        owner: milter-manager
        group: postfix
        mode: 0750
    - name: Configure milter manager
      copy:
        src: "{{ item }}"
        dest: /{{ item }}
      with_items:
        - etc/default/milter-manager
      notify:
        - Restart milter manager

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
    - name: Update /etc/aliases
      command: postalias /etc/aliases
    - name: Restart Postfix
      service:
        name: postfix
        state: restarted
    - name: Restart milter-greylist
      service:
        name: milter-greylist
        state: restarted
    - name: Restart milter manager
      service:
        name: milter-manager
        state: restarted
