# -*- ruby -*-

base_dir = File.join(__dir__, "..", "vendor", "arrow-dist", "cpp-linux")
base_dir = File.expand_path(base_dir)

task :apt do
  cd(base_dir) do
    ruby("-S", "rake", "apt")
  end
  sh("rsync", "-av", "--delete",
     "#{base_dir}/apt/repositories/",
     "apt/repositories/")
end

task :yum do
  cd(base_dir) do
    ruby("-S", "rake", "yum")
  end
  sh("rsync", "-av", "--delete",
     "#{base_dir}/yum/repositories/",
     "yum/repositories/")
end
