# -*- ruby -*-

require_relative "../package-task"

class ApacheArrowPackageTask < PackageTask
  def initialize
    super("apache-arrow", "0.2.1.20170320")
    @rpm_package = "arrow"
  end

  private
  def define_archive_task
    file @archive_name do
      cd("../vendor/arrow") do
        sh("git", "archive", "HEAD",
           "--prefix", "#{@archive_base_name}/",
           "--output", @archive_name)
        sh("tar", "xf", @archive_name)
        rm_f(@archive_name)

        download("https://github.com/google/flatbuffers/archive/v1.6.0.tar.gz",
                 "#{@archive_base_name}/vendor/flatbuffers/")

        rapidjson_version = "1.1.0"
        rapidjson_tar_gz = "v#{rapidjson_version}.tar.gz"
        download("https://github.com/miloyip/rapidjson/archive/#{rapidjson_tar_gz}",
                 ".")
        sh("tar", "xf", rapidjson_tar_gz)
        mv("rapidjson-#{rapidjson_version}",
           "#{@archive_base_name}/vendor/rapidjson/")
        rm_f(rapidjson_tar_gz)

        sh("tar", "czf", @full_archive_name, @archive_base_name)
        rm_rf(@archive_base_name)
      end
    end
  end

  def rpm_depended_packages
    [
      "pkg-config",
      "cmake",
      "boost-devel",
      "git",
      "jemalloc-devel",
      "gtk-doc",
      "gobject-introspection-devel",
    ]
  end

  def deb_depended_packages
    [
      "debhelper",
      "pkg-config",
      "cmake",
      "git",
      "libboost-system-dev",
      "libboost-filesystem-dev",
      "libjemalloc-dev",
      "gtk-doc-tools",
      "libgirepository1.0-dev",
      "libglib2.0-doc",
    ]
  end
end

task = ApacheArrowPackageTask.new
task.define
