# -*- ruby -*-

require_relative "../package-task"

class ApacheArrowPackageTask < PackageTask
  def initialize
    super("apache-arrow", "0.2.1.20170320")
    @rpm_package = "arrow"
  end

  private
  def define_archive_task
    file @archive_name do
      cd("../vendor/arrow") do
        sh("git", "archive", "HEAD",
           "--prefix", "#{@archive_base_name}/",
           "--output", @full_archive_name)
      end
    end
  end

  def rpm_depended_packages
    [
      "pkg-config",
      "cmake",
      "boost-devel",
      "git",
      "jemalloc-devel",
      "gtk-doc",
      "gobject-introspection-devel",
    ]
  end

  def deb_depended_packages
    [
      "debhelper",
      "pkg-config",
      "cmake",
      "git",
      "libboost-system-dev",
      "libboost-filesystem-dev",
      "libjemalloc-dev",
      "gtk-doc-tools",
      "libgirepository1.0-dev",
      "libglib2.0-doc",
    ]
  end
end

task = ApacheArrowPackageTask.new
task.define
